# Generated by Django 4.2.1 on 2023-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mood", models.IntegerField()),
                ("content", models.TextField()),
                ("achievement_rate", models.FloatField()),
            ],
        ),
    ]
