# Generated by Django 4.2.1 on 2023-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=15)),
                ("join_date", models.DateField()),
                ("point", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("illuminance", models.FloatField()),
                ("soil_moisture", models.FloatField()),
            ],
        ),
    ]
